### ISSUE TITLE
插件预览时SText有从小变大的动画，编译后则没有。

### ISSUE THREAD

**Issue by ZhengLongBing** [Surrealism-All/SurrealismUI#16]

**Comment by syf20020816** [comment]
你可以尝试在原生text组件上添加动画，进行编译测试，若同样无动画，则需要向slint提交issue

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Longbing Zheng ***@***.***>
Sent: Wednesday, December 27, 2023 12:38:39 PM
To: Surrealism-All/SurrealismUI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Surrealism-All/SurrealismUI] 插件预览时SText有从小变大的动画，编译后则没有。 (Issue #16)


―

**Comment by ZhengLongBing** [comment]
原生text组件上添加动画，还是一样的问题

**Comment by ZhengLongBing** [comment]
老哥，你去slint提个issue，我也不知道怎么用英文说这个。

**Comment by syf20020816** [comment]
目前测试下来动画正常

https://github.com/Surrealism-All/SurrealismUI/assets/92167095/e831c638-f274-4045-9839-87f0e9fb400c
