### ISSUE TITLE
提个小问题

### ISSUE THREAD

**Issue by Vjze** [Surrealism-All/SurrealismUI#19]
sselect的下拉card宽度异常，设置的宽度只在点击card生效。
![image](https://github.com/Surrealism-All/SurrealismUI/assets/99671889/46bb1fe9-0bdb-4a96-8f7c-300650e1c80d)

**Comment by syf20020816** [comment]
请附带具体代码以供参考

**Comment by Vjze** [comment]
// btw-select := SSelect {
                //     width: 380px;
                //     options: btws;
                //     placeholder: "选择标签模板";
                //     theme: Light;
                //     changed(index,label) => {
                //         btws-select-value = label;
                //         btw-status = "已选择";
                //         self.close()
                //     }
                // }

**Comment by Vjze** [comment]
其实我个人觉得这个self.close()应该添加在你的源代码里的，点击之后收起下拉选项，这才是最常用的模式吧

**Comment by syf20020816** [comment]
请注意，设置宽度使用card-width当组件是继承SCard时

**Comment by syf20020816** [comment]
另外close方法是一种可靠的关闭方式，或许用户并不希望选择结束后关闭选项，所以这是可自主控制的

**Comment by syf20020816** [comment]
目前所有组件的文档已经更新，请查看wiki： https://github.com/Surrealism-All/SurrealismUI/wiki
