### ISSUE TITLE
Light 主题下 SSelect 字体颜色看不清 可能需要给 SText 加个颜色

### ISSUE THREAD

**Issue by timsaya** [Surrealism-All/SurrealismUI#23]
大佬，你好。

![截屏2024-01-18 10 09 11](https://github.com/Surrealism-All/SurrealismUI/assets/155968641/8c40a2ef-d7a2-4132-97d9-dace3cc3ade9)

<img width="770" alt="截屏2024-01-18 10 08 37" src="https://github.com/Surrealism-All/SurrealismUI/assets/155968641/eb299baa-3038-4613-9c33-de8b51d3c68d">

**Comment by syf20020816** [comment]
您好，我的建议有4个，如果着急可使用前3个
1. 直接修改themes包src目录下的theme.slint文件中ROOT_STYLES这个global下的sur-theme-colors中的dark的font颜色
2. 在select组件的placeholder位置添加theme:Themes.Light
3. 同2但添加color自行定义
4. 等待周末的0.3.4版本，它将处理现有问题

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: timsaya ***@***.***>
Sent: Thursday, January 18, 2024 10:10:37 AM
To: Surrealism-All/SurrealismUI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Surrealism-All/SurrealismUI] Light 主题下 SSelect 字体颜色看不清 可能需要给 SText 加个颜色 (Issue #23)


大佬，你好。

2024-01-18.10.09.11.png (view on web)<https://github.com/Surrealism-All/SurrealismUI/assets/155968641/8c40a2ef-d7a2-4132-97d9-dace3cc3ade9>

2024-01-18.10.08.37.png (view on web)<https://github.com/Surrealism-All/SurrealismUI/assets/155968641/eb299baa-3038-4613-9c33-de8b51d3c68d>

―
