### ISSUE TITLE
请问怎么disable一个SButton?

### ISSUE THREAD

**Issue by chaobaicai** [Surrealism-All/SurrealismUI#29]
SurrealismUI的组件做的好漂亮，有需求要禁用按钮，不知道怎么做？

**Comment by syf20020816** [comment]
禁用目前可以通过在按钮外包裹TouchArea进行处理，但这似乎对使用者的体验并不好，我将在下个版本中为按钮添加禁用状态来提供一种方便的方式进行操作

下个版本的发版日期3月24日

**Comment by chaobaicai** [comment]
还有个小需求，SDialog显示后，点击外层的TouchArea会关闭对话框，可不可以导出一个property给用户设置。

**Comment by syf20020816** [comment]
> 还有个小需求，SDialog显示后，点击外层的TouchArea会关闭对话框，可不可以导出一个property给用户设置。

你可以使用SDialog的`is-show`属性

- in-out property <bool> is-show: Dialog is show or not

**Comment by syf20020816** [comment]
抱歉，我好像误会了你的需求，看来你是想要点击外层不关闭SDialog
这个确实是个很好的建议，它同样会在下个版本被处理

**Comment by syf20020816** [comment]
this issue has been solved in 20240320
