### ISSUE TITLE
请教一个问题，cargo build 打包成exe之后，双击执行这个exe，会出现一个cmd框，请问应该执行哪个编译选项，感谢解答

### ISSUE THREAD

**Issue by FiveKm** [Surrealism-All/SurrealismUI#30]

**Comment by syf20020816** [comment]
#![windows_subsystem = "windows"]

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: FiveKm ***@***.***>
Sent: Tuesday, April 2, 2024 3:15:28 PM
To: Surrealism-All/SurrealismUI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Surrealism-All/SurrealismUI] 请教一个问题，cargo build 打包成exe之后，双击执行这个exe，会出现一个cmd框，请问应该执行哪个编译选项，感谢解答 (Issue #30)


―
