### ISSUE TITLE
能不能开发一个示例项目

### ISSUE THREAD

**Issue by w858269620** [Surrealism-All/SurrealismUI#33]
能不能开发一个示例项目，类似于element-plus-admin这种，对于初学者来说可以根据示例进行开发

**Comment by syf20020816** [comment]
好的，我会尽快开启这样的工作，如果你还需要任何帮助可以加入Discord与我一起讨论

Okay, I will start working on this as soon as possible. If you need any further help, you can join Discord and discuss with me

**Comment by w858269620** [comment]
能不能给个微信群或qq群之类的，方便沟通

**Comment by syf20020816** [comment]
抱歉，我暂时没有群，但你可以使用Discord加入
![IMG_20240409_091537.jpg](https://github.com/Surrealism-All/SurrealismUI/assets/92167095/422282cd-b58f-4263-a9ad-ec8dfaebb906)

**Comment by syf20020816** [comment]
this is an example for SurrealismUI:
https://github.com/Surrealism-All/Discord_SurrealismUI

**Comment by syf20020816** [comment]
you can quickly learn how to use common widgets
but if you wanna learn more, SurrealismUI Book is better
