### ISSUE TITLE
tests/src/star.slint,SStar bug?

### ISSUE THREAD

**Issue by iincity** [Surrealism-All/SurrealismUI#38]
![image](https://github.com/Surrealism-All/SurrealismUI/assets/5435797/9a52e19c-24df-4262-83ca-8374bb581466)
![image](https://github.com/Surrealism-All/SurrealismUI/assets/5435797/0b8bcf1e-86ae-45ea-b8b4-a1891d889efc)
![image](https://github.com/Surrealism-All/SurrealismUI/assets/5435797/16dd2c37-a50d-4f33-baae-7eab2e6f3937)
![image](https://github.com/Surrealism-All/SurrealismUI/assets/5435797/86ee2800-75ad-479f-8f57-2af73e0a0219)
![image](https://github.com/Surrealism-All/SurrealismUI/assets/5435797/7984a718-4383-46e8-a59d-69a539d6ebb6)

**Comment by syf20020816** [comment]
It seems often happened when quickly press or click star, I will try to solve it in V0.5

**Comment by syf20020816** [comment]
This seems to be caused by slint failure in loading images, and there is no problem with the algorithm. I am currently testing the compiled results

**Comment by syf20020816** [comment]
At present, this issue only occurs on VSCode LSP, and it seems that this issue did not occur after compilation
