### ISSUE TITLE
Specifying id doesnt work for sub-menu data

### ISSUE THREAD

**Issue by manish-ach** [Surrealism-All/SurrealismUI#48]
Both menu-data and sub-menu-data have separate index count as normal, but for example if i have 2 icons in menu-data with id 0 and 1, then again 2 in sub-menu-data. The id for sub-menu-data seems to also start from 0. Manually setting up id as 2 or 3 doesnt work. When using debug(index) inside change callback it still outputs 0 and 1 for the items in submenu data whose value has been manually set to 2 and 3.

**Comment by syf20020816** [comment]
can you show me your slint code about that?

**Comment by manish-ach** [comment]
sorry my bad, i somehow thought item id was supposed to work as index. i was using if condition where if the index matched the menu it would open specific popover. though it seems like for menu data and sub menu data index are totally different i.e. the index for first item in menu-data is 0 and for sub-menu data first item index is also 0.

i later fixed it by using item.id instead of index though. Please correct me if I am wrong though.
here is the part of code that was problematic which has been fixed now.
```
menu2 := SMenu {
        menu-data: [
          {
            icon: @image-url("../assets/file.svg"),
            name: "open",
            id: 0
          },
          {
            icon: @image-url("../assets/search.svg"),
            name: "open",
            id: 1
          }
        ];


    sub-menu-data: [
      {
        icon: @image-url("../assets/avatar.svg"),
        name: "profile",
        id: 2
      },
      {
        icon: @image-url("../assets/setting-two.svg"),
        name: "setting",
        id: 3
      }
    ];

        change(index, item) => {
          if item.id == 0 {
            draw.close();
            menu1.active = 0;
          }
          if item.id == 1 {
            self.active = 1;
          } 
          if item.id == 2 {
            self.active =2;
          }
          if item.id == 3 {
            self.active =3;
          }
        }
      }
      ```
     this is the code that i used which worked, in the previous one for which i raised issue was using index instead of item.id due to which setting id did nothing.
