### ISSUE TITLE
[建议]建议README.md中的说明不要中英文穿插

### ISSUE THREAD

**Issue by worldyuan** [Surrealism-All/SurrealismUI#51]
建议整个段都是中文，然后再是英文，或者单独分成两个文件，上面有个连接可以切换，中英文穿插读起来体验很不好，本来只需要4页的，现在需要8页。

**Comment by syf20020816** [comment]
I don't know which version of the README you're looking at. Chinese only appears in the Updates section

**Comment by syf20020816** [comment]
When you use SurrealismUI, you should use releases asserts which not has README.md
